/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        authorLabel = new javax.swing.JLabel();
        datoPane = new javax.swing.JPanel();
        addTolista1Button = new javax.swing.JButton();
        lista1Pane = new javax.swing.JPanel();
        lista1ScrollPane = new javax.swing.JScrollPane();
        lista1Lista = new javax.swing.JList();
        resetSelectionButton = new javax.swing.JButton();
        modoPane = new javax.swing.JPanel();
        simplebutton = new javax.swing.JToggleButton();
        invervaloSimpleButton = new javax.swing.JToggleButton();
        multiplesIntervalosButton = new javax.swing.JToggleButton();
        lista2Pane = new javax.swing.JPanel();
        lista2ScrollPane = new javax.swing.JScrollPane();
        lista2Lista = new javax.swing.JList();
        resetListaButton = new javax.swing.JButton();
        borraSeleccionButton = new javax.swing.JButton();
        ordenaListaButton = new javax.swing.JButton();
        addTolista2Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo Listas y Botones");

        authorLabel.setText("Héctor Garbisu DIU 2015");

        datoPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Dato"));

        javax.swing.GroupLayout datoPaneLayout = new javax.swing.GroupLayout(datoPane);
        datoPane.setLayout(datoPaneLayout);
        datoPaneLayout.setHorizontalGroup(
            datoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        datoPaneLayout.setVerticalGroup(
            datoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        addTolista1Button.setText("A Lista1 ->");

        lista1Pane.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista 1"));

        lista1Lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lista1ScrollPane.setViewportView(lista1Lista);

        resetSelectionButton.setText("Reset Seleción");

        modoPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Modo de Selección"));

        buttonGroup.add(simplebutton);
        simplebutton.setText("jToggleButton1");

        buttonGroup.add(invervaloSimpleButton);
        invervaloSimpleButton.setText("jToggleButton2");

        buttonGroup.add(multiplesIntervalosButton);
        multiplesIntervalosButton.setText("jToggleButton3");

        javax.swing.GroupLayout modoPaneLayout = new javax.swing.GroupLayout(modoPane);
        modoPane.setLayout(modoPaneLayout);
        modoPaneLayout.setHorizontalGroup(
            modoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modoPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simplebutton)
                    .addComponent(invervaloSimpleButton)
                    .addComponent(multiplesIntervalosButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        modoPaneLayout.setVerticalGroup(
            modoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modoPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simplebutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invervaloSimpleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multiplesIntervalosButton)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout lista1PaneLayout = new javax.swing.GroupLayout(lista1Pane);
        lista1Pane.setLayout(lista1PaneLayout);
        lista1PaneLayout.setHorizontalGroup(
            lista1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lista1PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lista1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lista1PaneLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(resetSelectionButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lista1PaneLayout.createSequentialGroup()
                        .addGroup(lista1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lista1ScrollPane)
                            .addComponent(modoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        lista1PaneLayout.setVerticalGroup(
            lista1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lista1PaneLayout.createSequentialGroup()
                .addComponent(lista1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetSelectionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lista2Pane.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista 2"));

        lista2Lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lista2ScrollPane.setViewportView(lista2Lista);

        resetListaButton.setText("Reset Lista");

        borraSeleccionButton.setText("Borra Selección");

        ordenaListaButton.setText("Ordena Lista");

        javax.swing.GroupLayout lista2PaneLayout = new javax.swing.GroupLayout(lista2Pane);
        lista2Pane.setLayout(lista2PaneLayout);
        lista2PaneLayout.setHorizontalGroup(
            lista2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lista2PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lista2ScrollPane)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lista2PaneLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(lista2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(borraSeleccionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetListaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ordenaListaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        lista2PaneLayout.setVerticalGroup(
            lista2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lista2PaneLayout.createSequentialGroup()
                .addComponent(lista2ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetListaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borraSeleccionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ordenaListaButton)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        addTolista2Button.setText("A lista 2 ->");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(datoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addTolista1Button)
                        .addGap(10, 10, 10)
                        .addComponent(lista1Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(addTolista2Button)
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(511, Short.MAX_VALUE)
                    .addComponent(lista2Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(addTolista2Button)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lista1Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(addTolista1Button)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(authorLabel))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lista2Pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTolista1Button;
    private javax.swing.JButton addTolista2Button;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JButton borraSeleccionButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel datoPane;
    private javax.swing.JToggleButton invervaloSimpleButton;
    private javax.swing.JList lista1Lista;
    private javax.swing.JPanel lista1Pane;
    private javax.swing.JScrollPane lista1ScrollPane;
    private javax.swing.JList lista2Lista;
    private javax.swing.JPanel lista2Pane;
    private javax.swing.JScrollPane lista2ScrollPane;
    private javax.swing.JPanel modoPane;
    private javax.swing.JToggleButton multiplesIntervalosButton;
    private javax.swing.JButton ordenaListaButton;
    private javax.swing.JButton resetListaButton;
    private javax.swing.JButton resetSelectionButton;
    private javax.swing.JToggleButton simplebutton;
    // End of variables declaration//GEN-END:variables
}
