
import java.util.Collections;
import java.util.List;
import javax.swing.ListSelectionModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        authorLabel = new javax.swing.JLabel();
        datoPane = new javax.swing.JPanel();
        datoTextField = new javax.swing.JTextField();
        addTolista1Button = new javax.swing.JButton();
        lista1Pane = new javax.swing.JPanel();
        lista1ScrollPane = new javax.swing.JScrollPane();
        lista1Lista = new javax.swing.JList();
        resetSelectionButton = new javax.swing.JButton();
        modoPane = new javax.swing.JPanel();
        simplebutton = new javax.swing.JToggleButton();
        invervaloSimpleButton = new javax.swing.JToggleButton();
        multiplesIntervalosButton = new javax.swing.JToggleButton();
        lista2Pane = new javax.swing.JPanel();
        lista2ScrollPane = new javax.swing.JScrollPane();
        lista2Lista = new javax.swing.JList();
        resetListaButton = new javax.swing.JButton();
        borraSeleccionButton = new javax.swing.JButton();
        ordenaListaButton = new javax.swing.JButton();
        addTolista2Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo Listas y Botones");

        authorLabel.setText("Héctor Garbisu DIU 2015");

        datoPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Dato"));

        datoTextField.setText(" ");

        javax.swing.GroupLayout datoPaneLayout = new javax.swing.GroupLayout(datoPane);
        datoPane.setLayout(datoPaneLayout);
        datoPaneLayout.setHorizontalGroup(
            datoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datoPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        datoPaneLayout.setVerticalGroup(
            datoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(datoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        addTolista1Button.setText("A Lista1 ->");
        addTolista1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTolista1ButtonActionPerformed(evt);
            }
        });

        lista1Pane.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista 1"));

        lista1ScrollPane.setViewportView(lista1Lista);

        resetSelectionButton.setText("Reset Seleción");
        resetSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetSelectionButtonActionPerformed(evt);
            }
        });

        modoPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Modo de Selección"));

        buttonGroup.add(simplebutton);
        simplebutton.setText("Simple");
        simplebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simplebuttonActionPerformed(evt);
            }
        });

        buttonGroup.add(invervaloSimpleButton);
        invervaloSimpleButton.setText("Intervalo Simple");
        invervaloSimpleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invervaloSimpleButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(multiplesIntervalosButton);
        multiplesIntervalosButton.setText("Multiples Intervalos");
        multiplesIntervalosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplesIntervalosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modoPaneLayout = new javax.swing.GroupLayout(modoPane);
        modoPane.setLayout(modoPaneLayout);
        modoPaneLayout.setHorizontalGroup(
            modoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modoPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(multiplesIntervalosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invervaloSimpleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simplebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        modoPaneLayout.setVerticalGroup(
            modoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modoPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simplebutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invervaloSimpleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multiplesIntervalosButton)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout lista1PaneLayout = new javax.swing.GroupLayout(lista1Pane);
        lista1Pane.setLayout(lista1PaneLayout);
        lista1PaneLayout.setHorizontalGroup(
            lista1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lista1PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lista1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetSelectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lista1ScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(modoPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        lista1PaneLayout.setVerticalGroup(
            lista1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lista1PaneLayout.createSequentialGroup()
                .addComponent(lista1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetSelectionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lista2Pane.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista 2"));

        lista2ScrollPane.setViewportView(lista2Lista);

        resetListaButton.setText("Reset Lista");
        resetListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetListaButtonActionPerformed(evt);
            }
        });

        borraSeleccionButton.setText("Borra Selección");
        borraSeleccionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borraSeleccionButtonActionPerformed(evt);
            }
        });

        ordenaListaButton.setText("Ordena Lista");
        ordenaListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenaListaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lista2PaneLayout = new javax.swing.GroupLayout(lista2Pane);
        lista2Pane.setLayout(lista2PaneLayout);
        lista2PaneLayout.setHorizontalGroup(
            lista2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lista2PaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lista2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resetListaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lista2ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(borraSeleccionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(ordenaListaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lista2PaneLayout.setVerticalGroup(
            lista2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lista2PaneLayout.createSequentialGroup()
                .addComponent(lista2ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetListaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borraSeleccionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ordenaListaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addTolista2Button.setText("A lista 2 ->");
        addTolista2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTolista2ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(datoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addTolista1Button)
                        .addGap(10, 10, 10)
                        .addComponent(lista1Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(addTolista2Button)
                .addGap(18, 18, 18)
                .addComponent(lista2Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lista1Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(addTolista1Button))
                            .addComponent(datoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(authorLabel))))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lista2Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTolista2Button))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTolista1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTolista1ButtonActionPerformed
        String dato = datoTextField.getText();
        if((dato==null) || dato.isEmpty()) return;
        datoTextField.setText("");
        int len = lista1Lista.getModel().getSize();
        if(len==0){
            String [] valores = new String[1];
            valores[0] = dato;
            lista1Lista.setListData(valores);
        }
        else{
            lista1Lista.setSelectionInterval(0, len-1);
            List valores = lista1Lista.getSelectedValuesList();
            valores.add(dato);
            lista1Lista.setListData(valores.toArray());
        }
    }//GEN-LAST:event_addTolista1ButtonActionPerformed

    private void simplebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simplebuttonActionPerformed
        // TODO add your handling code here:
        lista1Lista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }//GEN-LAST:event_simplebuttonActionPerformed

    private void invervaloSimpleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invervaloSimpleButtonActionPerformed
        // TODO add your handling code here:
        lista1Lista.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
    }//GEN-LAST:event_invervaloSimpleButtonActionPerformed

    private void multiplesIntervalosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplesIntervalosButtonActionPerformed
        // TODO add your handling code here:
        lista1Lista.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);        
    }//GEN-LAST:event_multiplesIntervalosButtonActionPerformed

    private void resetSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetSelectionButtonActionPerformed
        // TODO add your handling code here:
        try{
       lista1Lista.setSelectedIndices(null);
        }catch(NullPointerException e){}
    }//GEN-LAST:event_resetSelectionButtonActionPerformed

    private void addTolista2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTolista2ButtonActionPerformed
        // TODO add your handling code here:
        List seleccionados = lista1Lista.getSelectedValuesList();
        lista2Lista.setListData(seleccionados.toArray());
    }//GEN-LAST:event_addTolista2ButtonActionPerformed

    private void resetListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetListaButtonActionPerformed
        // TODO add your handling code here:
        List seleccionados = lista2Lista.getSelectedValuesList();
        seleccionados.clear();
        lista2Lista.setListData(seleccionados.toArray());
    }//GEN-LAST:event_resetListaButtonActionPerformed

    private void borraSeleccionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borraSeleccionButtonActionPerformed
        // TODO add your handling code here:
        List seleccionados = lista2Lista.getSelectedValuesList();
        if(seleccionados.isEmpty()) return;
        int len = lista2Lista.getModel().getSize();
        lista2Lista.setSelectionInterval(0, len-1);
        List listatotal = lista2Lista.getSelectedValuesList();
        listatotal.removeAll(seleccionados);
        lista2Lista.setListData(listatotal.toArray());
    }//GEN-LAST:event_borraSeleccionButtonActionPerformed

    private void ordenaListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenaListaButtonActionPerformed
        // TODO add your handling code here:
        int len = lista2Lista.getModel().getSize();
        lista2Lista.setSelectionInterval(0, len-1);
        List listatotal = lista2Lista.getSelectedValuesList();
        Collections.sort(listatotal);
        lista2Lista.setListData(listatotal.toArray());
    }//GEN-LAST:event_ordenaListaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windwows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTolista1Button;
    private javax.swing.JButton addTolista2Button;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JButton borraSeleccionButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel datoPane;
    private javax.swing.JTextField datoTextField;
    private javax.swing.JToggleButton invervaloSimpleButton;
    private javax.swing.JList lista1Lista;
    private javax.swing.JPanel lista1Pane;
    private javax.swing.JScrollPane lista1ScrollPane;
    private javax.swing.JList lista2Lista;
    private javax.swing.JPanel lista2Pane;
    private javax.swing.JScrollPane lista2ScrollPane;
    private javax.swing.JPanel modoPane;
    private javax.swing.JToggleButton multiplesIntervalosButton;
    private javax.swing.JButton ordenaListaButton;
    private javax.swing.JButton resetListaButton;
    private javax.swing.JButton resetSelectionButton;
    private javax.swing.JToggleButton simplebutton;
    // End of variables declaration//GEN-END:variables
}
